version: '3.8'
services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: infinity-testing-postgres-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: infinity_db
    networks:
      - infinity-network-2

networks:
  infinity-network-2:
